In [2]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('task1_vgg2.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
        img_array = np.array(im)
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
        name="None matching"
        
        if(pred[0][0]):
            name='Deepa'
        elif(pred[0][1]):
            name='Kirti'
        elif(pred[0][2]):
            name='Siddharth'
            
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1)==13:
        video_capture.release()
        cv2.destroyAllWindows()

<>:21: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:21: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-2-e2dc9793224b>:21: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


[[0.0000000e+00 5.5680525e-29 1.0000000e+00]]
[[0.0000000e+00 9.5336424e-20 1.0000000e+00]]
[[0.000000e+00 8.941702e-25 1.000000e+00]]
[[0.0000000e+00 1.5720977e-24 1.0000000e+00]]
[[0.000000e+00 9.087444e-23 1.000000e+00]]
[[0.0000000e+00 1.2724412e-28 1.0000000e+00]]
[[0.0000000e+00 2.1373207e-28 1.0000000e+00]]
[[0.0000000e+00 2.4722169e-26 1.0000000e+00]]
[[0.0000000e+00 1.0120324e-27 1.0000000e+00]]
[[0.0000000e+00 1.1603171e-22 1.0000000e+00]]
[[0.0000000e+00 3.6054068e-26 1.0000000e+00]]
[[0.0000000e+00 2.5675966e-30 1.0000000e+00]]
[[0.0000000e+00 2.1396984e-32 1.0000000e+00]]
[[0.0000000e+00 1.3398618e-26 1.0000000e+00]]
[[0.0000000e+00 1.9865623e-29 1.0000000e+00]]
[[0.000000e+00 7.162529e-25 1.000000e+00]]
[[0.000000e+00 5.955205e-26 1.000000e+00]]
[[0.0000000e+00 7.3423817e-31 1.0000000e+00]]
[[0.0000e+00 1.7965e-26 1.0000e+00]]
[[0.000000e+00 2.412722e-24 1.000000e+00]]
[[0.000000e+00 6.414442e-28 1.000000e+00]]
[[0.000000e+00 9.258885e-27 1.000000e+00]]
[[0.0000000e+00 3.

error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\modules\highgui\src\window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
